language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt || python -m pip install -r requirements.txt
# Build script (If successfully built - no errors)
script:
  - python setup.py --version
  - python r3con1z3r/cli.py -d google.com
  - cat google.com-r3con1z3r.html
  - rm google.com-r3con1z3r.html
  - python setup.py install
  - r3con1z3r -d google.com
  - pip uninstall r3con1z3r -y
cache: pip
deploy:
  provider: pypi
  user: "gaphy"
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    branch: master
after_deploy:
  # install from pip package
  - pip install r3con1z3r
  - r3con1z3r
